### PR TITLE
fix: Update FP8 sf layout for Blackwell and relax blockwise GEMM assertions

### LINKED ISSUE #3118: Unable to run Deepseek R1 on blackwell
### System Info

8xB200 system

Started a docker container from TensorRT-LLM codebase as follows:
make -C docker build

Run the container as
docker run --rm -it \
        --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --gpus=all \
        --volume ${PWD}:/code/tensorrt_llm \
        --workdir /code/tensorrt_llm \
        tensorrt_llm/devel:latest

git sha dc0463b0e2f62a0aaaa3b018673440d3b39d594a

### Who can help?

_No response_

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

trtllm-serve deepseek-ai/DeepSeek-R1 --extra_llm_api_options options-lat.yml --port 10001

Where contents of options-lat are:
```yaml
enable_attention_dp: false
pytorch_backend_config:
  enable_overlap_scheduler: true
  use_cuda_graph: true
  cuda_graph_batch_sizes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
speculative_config:
  decoding_type: MTP
  num_nextn_predict_layers: 3
kv_cache_config:
  free_gpu_memory_fraction: 0.75
backend: pytorch
tensor_parallel_size: 8
moe_expert_parallel_size: 8
```

### Expected behavior

The model server should start up 

### actual behavior

File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/attention.py", line 437, in forward
    compressed_q, compressed_kv, k_pe = self.fused_a(
                                        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/linear.py", line 409, in forward
    output = self.apply_linear(input, self.weight, self.bias)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/linear.py", line 330, in apply_linear
    output = torch.ops.trtllm.fp8_block_scaling_gemm(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1123, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: N must be a multiple of 128, (N=2112)

### additional notes

The issue doesn't happen on Hopper, just Blackwell. I think this check is failing:
https://github.com/NVIDIA/TensorRT-LLM/blob/60d4dacc47ba18b3aed425dd4c5af8cbc8068169/cpp/tensorrt_llm/thop/fp8BlockScalingGemm.cpp#L135

### PR DESCRIPTION
**Pull request by chang-l**
This is to fix: https://github.com/NVIDIA/TensorRT-LLM/issues/3118

Some assertions in Blackwell FP8 blockwise gemm kernel may be misplaced.  Also, this PR handles the scaling factor layout mismatch for Blackwell kernels, compared to Hopper.

### CODE REVIEW

**Review by yibinl-nvidia — APPROVED** [review]
LGTM. Thanks for fixing the dim restriction!

File: cpp/tensorrt_llm/thop/fp8Quantize.cpp [hunk 1]
```diff
@@ -65,6 +66,18 @@ std::tuple<at::Tensor, at::Tensor> fp8_quantize_1x128(at::Tensor const& self)
...
+    if (tensorrt_llm::common::getSMVersion() == 100)
+    {
+        auto const num_n_blocks = (n + 127) / 128;
+        auto const act_scal_elesize = num_n_blocks * m_padded;
+        TORCH_CHECK(act_scal_elesize <= scaleFP8SF.numel(), "Scale tensor size mismatch. Expected at least ",
+            act_scal_elesize, " elements, got ", scaleFP8SF.numel());
+
+        // scaleFP8SF = scaleFP8SF[0:num_n_blocks, 0:m] // no 4-element alignment in blackwell
+        scaleFP8SF
+            = scaleFP8SF.slice(0, 0, act_scal_elesize).view({num_n_blocks, m_padded}).slice(1, 0, m).contiguous();
```
Comment (hlu1) [inline cpp/tensorrt_llm/thop/fp8Quantize.cpp:81]: `contiguous()` invokes a copy. Ideally, we should fix the kernel instead of using two ops on SM100. Can you add a TODO here?

Comment (chang-l) [reply cpp/tensorrt_llm/thop/fp8Quantize.cpp:81]: makes sense. Updated

**Review by hlu1 — APPROVED** [review]
